# Generated by Django 2.2 on 2020-10-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        ('user', '0002_auto_20201011_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attached_church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_church', to='church.Church'),
        ),
    ]
