# Generated by Django 2.2 on 2020-10-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
