# Generated by Django 2.2 on 2020-10-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201011_1357'),
        ('Job', '0002_proposal_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer')),
            ],
        ),
    ]
