# Generated by Django 2.2 on 2020-10-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201011_1357'),
        ('Job', '0003_auto_20201011_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[(1, 'Less than 1 week'), (2, 'Less than 1 month'), (3, '1 to 3 months'), (4, 'More than 3 months')], default=1, max_length=20)),
                ('body', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Volunteer')),
            ],
        ),
    ]
